# Deterministic global pool of traders + countries
COUNTRIES = ["USA","Nigeria","UK","Japan","India","China","Russia","Brazil","Germany","France"]

RANKING_TRADERS = [
    # (id, name)
    ("RobertGarcia", "Robert Garcia"), ("JamesLopez", "James Lopez"),
    ("WilliamRodriguez", "William Rodriguez"), ("DanielPerez", "Daniel Perez"),
    ("MatthewRamirez", "Matthew Ramirez"), ("EthanLee", "Ethan Lee"),
    ("BenjaminScott", "Benjamin Scott"), ("LucasBaker", "Lucas Baker"),
    ("HenryAllen", "Henry Allen"), ("SamuelGreen", "Samuel Green"),
    ("ThomasClark", "Thomas Clark"), ("JosephTurner", "Joseph Turner"),
    ("NathanielReed", "Nathaniel Reed"), ("AnthonyKing", "Anthony King"),
    ("DavidWright", "David Wright"), ("ChristopherHill", "Christopher Hill"),
    ("JonathanMitchell", "Jonathan Mitchell"), ("PatrickYoung", "Patrick Young"),
    ("JasonAdams", "Jason Adams"), ("KevinRoberts", "Kevin Roberts"),
    ("RyanNelson", "Ryan Nelson"), ("BrandonWalker", "Brandon Walker"),
    ("TylerScott", "Tyler Scott"), ("ZacharyMoore", "Zachary Moore"),
    ("ConnorWhite", "Connor White"), ("ShawnHarris", "Shawn Harris"),
    ("JustinReyes", "Justin Reyes"), ("DerekParker", "Derek Parker"),
    ("LoganBarnes", "Logan Barnes"), ("MasonBrooks", "Mason Brooks"),
    ("JordanFoster", "Jordan Foster"), ("ElijahCarter", "Elijah Carter"),
    ("CalebEvans", "Caleb Evans"), ("OwenMurphy", "Owen Murphy"),
    ("GavinDiaz", "Gavin Diaz"), ("NoahHughes", "Noah Hughes"),
    ("ColeSimmons", "Cole Simmons"), ("HunterButler", "Hunter Butler"),
    ("ChaseLong", "Chase Long"), ("MicahHayes", "Micah Hayes"),
    ("AdrianRoss", "Adrian Ross"), ("VictorColeman", "Victor Coleman"),
    ("XavierMorgan", "Xavier Morgan"), ("DominicGray", "Dominic Gray"),
    ("IsaacPeterson", "Isaac Peterson"), ("LeviWard", "Levi Ward"),
    ("MilesWatson", "Miles Watson"), ("MaxwellHoward", "Maxwell Howard"),
    ("JulianPrice", "Julian Price"), ("ChristianSanders", "Christian Sanders"),
    ("LiamHenderson", "Liam Henderson"), ("NicholasGibson", "Nicholas Gibson"),
    ("DiegoFernandez", "Diego Fernandez"), ("CarlosMendez", "Carlos Mendez"),
    ("JavierOrtega", "Javier Ortega"), ("LuisCastillo", "Luis Castillo"),
    ("MateoVargas", "Mateo Vargas"), ("AndresMorales", "Andres Morales"),
    ("JoseMartinez", "Jose Martinez"), ("PedroLopez", "Pedro Lopez"),
    ("VictorSantos", "Victor Santos"), ("RicardoAlvarez", "Ricardo Alvarez"),
    ("AhmedKhalid", "Ahmed Khalid"), ("OmarHassan", "Omar Hassan"),
    ("KarimAli", "Karim Ali"), ("YoussefSalem", "Youssef Salem"),
    ("IbrahimMahmoud", "Ibrahim Mahmoud"), ("AbdulRahman", "Abdul Rahman"),
    ("MustafaFarouk", "Mustafa Farouk"), ("HassanOmar", "Hassan Omar"),
    ("KwameMensah", "Kwame Mensah"), ("ChineduOkafor", "Chinedu Okafor"),
    ("SamuelAdeyemi", "Samuel Adeyemi"), ("OluwaseunAkin", "Oluwaseun Akin"),
    ("EmekaNwosu", "Emeka Nwosu"), ("JosephBello", "Joseph Bello"),
    ("MichaelOkon", "Michael Okon"), ("DanielChukwu", "Daniel Chukwu"),
    ("KenjiTanaka", "Kenji Tanaka"), ("HiroshiYamamoto", "Hiroshi Yamamoto"),
    ("TakashiKobayashi", "Takashi Kobayashi"), ("SatoshiNakamura", "Satoshi Nakamura"),
    ("DaichiFujimoto", "Daichi Fujimoto"), ("MinHoPark", "Min Ho Park"),
    ("JaeWooKim", "Jae Woo Kim"), ("SungHoLee", "Sung Ho Lee"),
    ("HirokiSuzuki", "Hiroki Suzuki"), ("YutoMatsumoto", "Yuto Matsumoto"),
    ("RaviKumar", "Ravi Kumar"), ("ArjunPatel", "Arjun Patel"),
    ("VikramSharma", "Vikram Sharma"), ("AnilMehta", "Anil Mehta"),
    ("RajeshSingh", "Rajesh Singh"), ("SanjayGupta", "Sanjay Gupta"),
    ("ChenWei", "Chen Wei"), ("LiMing", "Li Ming"),
    ("WangJun", "Wang Jun"), ("ZhaoLei", "Zhao Lei"),
    ("SunHao", "Sun Hao"), ("ZhangYong", "Zhang Yong"),
    ("DmitriIvanov", "Dmitri Ivanov"), ("SergeiPetrov", "Sergei Petrov"),
    ("AlexeiVolkov", "Alexei Volkov"), ("ViktorSmirnov", "Viktor Smirnov"),
    ("NikolaiPopov", "Nikolai Popov"), ("AndreiSokolov", "Andrei Sokolov"),
    ("OliviaHernandez", "Olivia Hernandez"), ("SophiaGonzalez", "Sophia Gonzalez"),
    ("MiaMartinez", "Mia Martinez"), ("IsabellaSanchez", "Isabella Sanchez"),
    ("CharlotteTorres", "Charlotte Torres"), ("AvaKing", "Ava King"),
    ("GraceAdams", "Grace Adams"), ("ChloeYoung", "Chloe Young"),
    ("EllaWright", "Ella Wright"), ("VictoriaHarris", "Victoria Harris"),
    ("EmmaWhite", "Emma White"), ("LilyHall", "Lily Hall"),
    ("ZoeParker", "Zoe Parker"), ("AmeliaStewart", "Amelia Stewart"),
    ("HarperBennett", "Harper Bennett"), ("ScarlettRivera", "Scarlett Rivera"),
    ("AriaFlores", "Aria Flores"), ("LaylaGomez", "Layla Gomez"),
    ("CamilaOrtiz", "Camila Ortiz"), ("PenelopeReed", "Penelope Reed"),
    ("RileyPowell", "Riley Powell"), ("NoraCook", "Nora Cook"),
    ("LillianRogers", "Lillian Rogers"), ("HannahSimmons", "Hannah Simmons"),
    ("EvelynFoster", "Evelyn Foster"), ("StellaCole", "Stella Cole"),
    ("EllieWard", "Ellie Ward"), ("HazelPeterson", "Hazel Peterson"),
    ("AuroraGray", "Aurora Gray"), ("SavannahEvans", "Savannah Evans"),
    ("PaisleyCollins", "Paisley Collins"), ("BrooklynDiaz", "Brooklyn Diaz"),
    ("ClaireHughes", "Claire Hughes"), ("SkylarRoss", "Skylar Ross"),
    ("LucyLong", "Lucy Long"), ("BellaButler", "Bella Butler"),
    ("VioletBarnes", "Violet Barnes"), ("NaomiPrice", "Naomi Price"),
    ("MayaHoward", "Maya Howard"), ("LeahWatson", "Leah Watson"),
    ("SadieHenderson", "Sadie Henderson"), ("AliceGibson", "Alice Gibson"),
    ("EvaSanders", "Eva Sanders"), ("EverlyWard", "Everly Ward"),
    ("MadelynGray", "Madelyn Gray"), ("KinsleyMorgan", "Kinsley Morgan"),
    ("AllisonRoss", "Allison Ross"), ("AnnaHayes", "Anna Hayes"),
    ("SarahBrooks", "Sarah Brooks"), ("JuliaParker", "Julia Parker"),
    ("NatalieScott", "Natalie Scott"), ("CarolineNelson", "Caroline Nelson"),
    ("FatimaZahra", "Fatima Zahra"), ("AishaHassan", "Aisha Hassan"),
    ("LaylaAbdullah", "Layla Abdullah"), ("MariamKhalil", "Mariam Khalil"),
    ("HudaSalem", "Huda Salem"), ("AmiraFarah", "Amira Farah"),
    ("NgoziOkeke", "Ngozi Okeke"), ("AdaezeNwankwo", "Adaeze Nwankwo"),
    ("ChiomaUche", "Chioma Uche"), ("FolakeAdeola", "Folake Adeola"),
    ("FunkeOlawale", "Funke Olawale"), ("TemiBalogun", "Temi Balogun"),
    ("AkiraTanaka", "Akira Tanaka"), ("YumiKawasaki", "Yumi Kawasaki"),
    ("AyaSuzuki", "Aya Suzuki"), ("SakuraYamamoto", "Sakura Yamamoto"),
    ("NaokoFujimoto", "Naoko Fujimoto"), ("JiwooPark", "Jiwoo Park"),
    ("EunseoKim", "Eunseo Kim"), ("HanaLee", "Hana Lee"),
    ("MinaChoi", "Mina Choi"), ("SooyeonHan", "Sooyeon Han"),
]

SUCCESS_TRADERS = {
    "male": [
        ("JohnDoeTrader", "John Doe", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/male1.jpeg"),
        ("AlexJohnson", "Alex Johnson", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/male2.jpeg"),
        ("MichaelBrown", "Michael Brown", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/male3.jpeg"),
        ("DavidMiller", "David Miller", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/male4.jpeg"),
        ("ChrisAnderson", "Chris Anderson", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/male5.jpeg"),
    ],
    "female": [
        ("JaneSmithPro", "Jane Smith", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/female1.jpeg"),
        ("EmilyDavis", "Emily Davis", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/female2.jpeg"),
        ("SarahWilson", "Sarah Wilson", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/female3.jpeg"),
        ("LauraTaylor", "Laura Taylor", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/female4.jpeg"),
        ("AnnaMartinez", "Anna Martinez", "https://raw.githubusercontent.com/OptionsTradingUni/Stockbot/main/images/female5.jpeg"),
    ],
}

SUCCESS_STORY_TEMPLATES = {
    "male": [
        "transformed a modest ${deposit} investment into an impressive ${profit} through a meticulously planned swing trade on AAPL.",
        "turned ${deposit} into a remarkable ${profit} by mastering the art of BTC HODL.",
        "flipped a ${deposit} stake into ${profit} with a bold NIKY pump riding move.",
        "achieved a stunning ${profit} profit from a strategic ETH DCA plan starting with ${deposit}.",
        "earned ${profit} through a clever SOL arbitrage play after investing ${deposit}.",
    ],
    "female": [
        "grew a ${deposit} investment into ${profit} with a disciplined TSLA scalping strategy.",
        "boosted ${deposit} into ${profit} with an early sniping move on DOGE.",
        "turned ${deposit} into ${profit} via a SHIB community flip.",
        "made ${profit} from a NVDA position trade starting with ${deposit}.",
        "grew ${deposit} into ${profit} with a GOOGL day trading plan.",
    ],
}

NEWS_CATALYSTS = {
    "stocks": [
        "surged after strong earnings",
        "climbed on analyst upgrade",
        "rallied on new product launch",
        "gained on partnership news",
        "spiked with positive sentiment",
    ],
    "crypto": [
        "pumped after whale accumulation",
        "rose on adoption news",
        "surged on protocol upgrade",
        "gained after exchange listing",
        "spiked with DeFi integration",
    ],
    "meme_coins": [
        "mooned after viral tweet",
        "pumped on community hype",
        "surged with influencer shoutout",
        "rocketed after Reddit buzz",
        "spiked on meme-driven volume",
    ],
}
